####################################################################################
# Certbot / letsencrypt module
#
# Because of certbot it's basically trivial to setup SSL.
# There are a couple of gotchas:
#
# If you don't run `certonly` then nginx will automatically update an
# enabled site. This is problematic for automation with ansible
#
# The renewal dry-run with stop and start nginx, but it starts without systemctl,
# This causes issues later when the handler itself restarts nginx. So the solution
# is to run it with --installer non
#
# also, as usual, thanks arch: https://wiki.archlinux.org/index.php/Certbot
#
####################################################################################
---
- name: Install required system packages for certbot
  apt:
    state: latest
    update_cache: yes
    name:
      - certbot
      - python-certbot-nginx
  tags:
    - nginx
    - letsencrypt

- name: Check if cert is already present
  stat: path={{ letsencrypt_cert_path }}/
  register: cert_exists
  tags:
    - nginx
    - letsencrypt

# run with certonly so it doesn't modify site-enabled sites
# Only run this when the cert exists
# Run this once for all subdomains, force overwrite for new subdomains?
- name: Certbot create certs
  shell: certbot certonly --nginx -n --email={{ letsencrypt_email }} --cert-name={{ domain }} --agree-tos --domains={{ all_domains }} --cert-name {{ domain }}
  when: cert_exists.stat.exists == False
  tags:
    - nginx
    - letsencrypt

# This config is included in the wildcard include in nginx.conf
- name: Add certbot config for nginx sites
  template:
    src: certbot.conf.j2
    dest: /etc/nginx/conf.d/001-certbot.conf
  tags:
    - nginx
    - letsencrypt

- lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    insertafter: 'include /etc/nginx/sites-enabled'
    line: 'include /etc/nginx/conf.d/*.conf;'

- lineinfile:
    path: /etc/nginx/sites-available/default
    state: present
    insertafter: 'listen \[::\]:80'
    line: |
      listen [::]:443 ssl ipv6only=on;
      listen 443 ssl;

- name: Make sure www-data user can access keys
  file:
    state: directory
    recurse: yes
    path: /etc/letsencrypt/live/
    owner: www-data
    group: www-data

# installer none will not start rogue nginx
- name: Certbot dry run renew test
  shell: certbot --installer none --dry-run renew
  tags:
    - nginx
    - letsencrypt
