---
- name: Setup my local mac
  hosts: local
  connection: local
  roles:
    - geerlingguy.homebrew
    - mac
  vars:
    - personal_user: flove
    - homebrew_cask_accept_external_apps: true
    - homebrew_taps:
        - hashicorp/tap
    - homebrew_installed_packages:
        - htop
        - tree
        - stow
        - wget
        - node
        - zsh
        - zile
        - watch
        - tmux
        - just
        - cowsay
        - git
        - postgresql
        - terraform
        - gpg
        - python
        - jq
        - sdm
        - hashicorp/tap/vault
    - homebrew_cask_apps:
        - firefox
        - spotify
        - rectangle
        - slack
        - docker
        - google-chrome
        - spotify
