#cloud-config
package_update: true
packages:
  - squid
  - apache2-utils
write_files:
  - path: /etc/squid/squid.conf
    content: |
      auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/htpasswd
      auth_param basic realm proxy
      acl authenticated proxy_auth REQUIRED
      http_access allow authenticated
      http_port 0.0.0.0:3128
      forwarded_for delete
runcmd:
  - htpasswd -b -c /etc/squid/htpasswd treasure GKDBPhj68YPf
  - systemctl enable squid
  - systemctl restart squid
  - ufw enable
  - ufw allow ssh
  - ufw allow 'Squid'
