---
- name: Copy Raspi banner
  copy:
    src: raspi-mod.sh
    dest: /home/pi/raspi-mod.sh
  tags:
    - pi
    - conf

- name: Install required Alsa packages
  apt:
    state: latest
    update_cache: yes
    name:
      - alsa-utils
  tags:
    - pi
    - spotify

- name: Adding personal user {{ user }} to groups for GPIO
  user: name={{ personal_user }}
        groups=pi,gpio,audio,video,spi,i2c,plugdev,netdev,input,adm,dialout,cdrom,games
        append=yes
  tags:
    - pi
    - conf

- name: Spotify tasks
  include: spotify.yml
  when: spotify_user is defined
