---
- name: Copy Raspi banner
  copy:
    src: raspi-mod.sh
    dest: /home/pi/raspi-mod.sh
  tags:
    - pi
    - conf

- name: Adding personal user {{ user }} to groups for GPIO
  user: name={{ personal_user }}
        groups=pi,gpio,audio,video,spi,i2c,plugdev,netdev,input,adm,dialout,cdrom,games
        append=yes
  tags:
    - pi
    - conf

- name: Spotify tasks
  include: spotify.yml
  when: spotify_user is defined

- name: Eink tasks
  include: eink.yml
