---
- name: Copy Raspi banner
  copy:
    src: raspi-mod.sh
    dest: /home/pi/raspi-mod.sh
  tags:
    - pi
    - conf

- name: Install required Alsa packages
  apt:
    state: latest
    update_cache: yes
    name:
      - alsa-utils
  tags:
    - pi
    - spotify

- name: Adding personal user {{ user }} to groups for GPIO
  user: name={{ personal_user }}
        groups=pi,gpio,audio,video,spi,i2c,plugdev,netdev,input,adm,dialout,cdrom,games
        append=yes
  tags:
    - pi
    - conf

- name: Creates Spotify opt and bin directories
  file:
    path: "{{ spotify_dir }}/bin"
    state: directory
  tags:
    - pi
    - spotify

- name: Download sha512 of binary
  get_url:
    url: https://github.com/Spotifyd/spotifyd/releases/download/{{ spotifyd_version }}/spotifyd-linux-armv6-slim.sha512
    dest: "{{ spotify_dir }}"
    mode: 666
  tags:
    - pi
    - spotify

- name: Get sha512 checksum
  shell: "cat /opt/spotify/spotifyd-linux-armv6-slim.sha512 | cut -d' ' -f1"
  register: sha512checksum
  tags:
    - pi
    - spotify

- name: Download Spotifyd
  get_url:
    url: https://github.com/Spotifyd/spotifyd/releases/download/{{ spotifyd_version }}/spotifyd-linux-armv6-slim.tar.gz
    mode: 666
    dest: /opt/spotify/
    checksum: sha512:{{ sha512checksum.stdout }}
  tags:
    - pi
    - spotify

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: "{{ spotify_dir }}/spotifyd-linux-armv6-slim.tar.gz"
    dest: "{{ spotify_dir }}/bin/"
    remote_src: yes
    mode: a+x
  tags:
    - pi
    - spotify

- name: Add Spotifyd.conf configuration file
  ansible.builtin.template:
    src: spotifyd.conf
    dest: "{{ spotify_dir }}/"
    owner: pi
    group: pi
    mode: u=rw
  register: conf_template
  tags:
    - pi
    - spotify
    - conf

- name: Add Spotifyd service file
  ansible.builtin.template:
    src: spotifyd.service
    dest: /etc/systemd/system/spotifyd.service
    owner: pi
    group: pi
    mode: 777
  register: service_template
  tags:
    - pi
    - spotify
    - conf
    - service

- name: Enable Spotifd service
  service:
    name: spotifyd
    state: started
    enabled: yes
    scope: system
  tags:
    - pi
    - spotify
    - service

- name: Restart modified Spotifyd Service
  service:
    name: spotifyd
    state: restarted
  when: service_template.changed or conf_template.changed
  tags:
    - pi
    - spotify
    - service
    - conf

# Attempt at getting dbus to work https://serverfault.com/a/906224
# dest: /etc/systemd/user/spotifyd.service
# /home/pi/.config/systemd/user/

# - name: Creates Spotify Service directory
#   file:
#     path: /home/pi/.config/systemd/user/
#     state: directory
#   tags:
#     - pi
#     - service
#     - spotify
# - name: Enable Dbus service
#   become_user: pi
#   ansible.builtin.systemd:
#     name: dbus
#     state: started
#     enabled: yes
#     scope: user
#   tags:
#     - pi
#     - service
#    - spotify

# - name: Enable Spotifd service
#   become: yes
#   ansible.builtin.systemd:
#     name: spotifyd
#     state: started
#     enabled: yes
#     scope: system
#   tags:
#     - pi
#     - spotify
#     - service
