#################################################
# Set Up some git apps
#################################################
---
- name: Git clone the portfolio app
  git:
    repo: https://github.com/fenimore/fenimore.github.io
    dest: /var/www/html/portfolio
  notify: wwww-data directory
  tags:
    - app

- name: Git clone the riddle app
  git:
    repo: https://github.com/{{ personal_github }}/devinettes-web
    dest: /var/www/html/devinettes
  notify: wwww-data directory
  tags:
    - app

- name: Upload homepage html and css
  copy:
    src: html/
    dest: /var/www/html/
  notify: wwww-data directory
  tags:
    - app

# TODO: set up sub domain instead
- name: Include the Wink Photo App
  include: wink.yml
